import type { DissentBriefV1 } from '@/core/contracts/brief';
import type { ArgumentV1 } from '@/core/contracts/argument';
import type { EvidenceV1 } from '@/core/contracts/evidence';

const NOW = '2026-09-21T15:30:00.000Z';
const OBSERVED_AT = '2026-09-21T15:28:45.000Z';

export const PROTOTYPE_EVIDENCE_ITEMS: EvidenceV1[] = [
  {
    id: 'ev_eth_last',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH/USDT spot last price is $2,642.50.',
    category: 'PRICE_ACTION',
    stance: 'NEUTRAL',
    nature: 'NUMERIC',
    observation: {
      type: 'LAST_PRICE',
      market: 'ETH/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/tickers?symbol=ETHUSDT',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
      rawSnapshot: { symbol: 'ETHUSDT', lastPr: '2642.50', high24h: '2680.00', low24h: '2588.10' },
    },
    value: '2642.50',
    unit: 'USDT',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_last',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC/USDT spot last price is $63,180.00.',
    category: 'PRICE_ACTION',
    stance: 'NEUTRAL',
    nature: 'NUMERIC',
    observation: {
      type: 'LAST_PRICE',
      market: 'BTC/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/tickers?symbol=BTCUSDT',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
      rawSnapshot: { symbol: 'BTCUSDT', lastPr: '63180.00', high24h: '63800.00', low24h: '62450.00' },
    },
    value: '63180.00',
    unit: 'USDT',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_ratio_last',
    thesisId: 'th_eth_btc_48h',
    claim: 'The aligned ETH/BTC price ratio is 0.04182.',
    category: 'PRICE_ACTION',
    stance: 'NEUTRAL',
    nature: 'DERIVED',
    observation: {
      type: 'LAST_PRICE',
      market: 'ETH/BTC',
      instrumentType: 'DERIVED_SPOT_PAIR',
      providerSymbol: 'ETHUSDT:BTCUSDT',
    },
    provenance: {
      sourceName: 'Dissent Spot Analytics Engine',
      sourceType: 'DERIVED_ANALYTICS',
      endpointOrLocator: 'dissent://analytics/ratio/ETHUSDT:BTCUSDT',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
      rawSnapshot: { ratio: 0.0418249, formula: 'ETH_LAST / BTC_LAST' },
    },
    value: '0.04182',
    unit: 'ratio',
    derivedFromEvidenceIds: ['ev_eth_last', 'ev_btc_last'],
    relatedAssumptionIds: ['asm_1', 'asm_2'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_vol_24h',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH 24h spot turnover reached $1.42B USD.',
    category: 'PRICE_ACTION',
    stance: 'SUPPORTING',
    nature: 'NUMERIC',
    observation: {
      type: 'BASE_VOLUME_24H',
      market: 'ETH/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget Public Spot API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/tickers',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 120,
      rawSnapshot: { usdtVolume: '1420500000', baseVolume: '537559' },
    },
    value: 1420500000,
    unit: 'USD',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_1'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_vol_24h',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC 24h spot turnover is $3.89B USD.',
    category: 'PRICE_ACTION',
    stance: 'NEUTRAL',
    nature: 'NUMERIC',
    observation: {
      type: 'BASE_VOLUME_24H',
      market: 'BTC/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Bitget Public Spot API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/tickers',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 120,
    },
    value: 3890000000,
    unit: 'USD',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_spread_1h',
    thesisId: 'th_eth_btc_48h',
    claim: 'The 1H return spread between ETH (+1.45%) and BTC (+0.32%) is +1.13 percentage points.',
    category: 'CORRELATION',
    stance: 'SUPPORTING',
    nature: 'DERIVED',
    observation: {
      type: 'RETURN_SPREAD',
      market: 'ETH/BTC',
      instrumentType: 'DERIVED_SPOT_PAIR',
      providerSymbol: 'ETHUSDT:BTCUSDT',
      interval: '1H',
    },
    provenance: {
      sourceName: 'Dissent Analytics Engine',
      sourceType: 'DERIVED_ANALYTICS',
      endpointOrLocator: 'dissent://analytics/spread/1h',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 120,
    },
    value: '+1.13',
    unit: 'percentage points',
    derivedFromEvidenceIds: ['ev_eth_last', 'ev_btc_last'],
    relatedAssumptionIds: ['asm_2'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_funding',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH perpetual funding rate is +0.0082% (balanced long/short cost).',
    category: 'FUNDING_RATE',
    stance: 'SUPPORTING',
    nature: 'NUMERIC',
    observation: {
      type: 'FUNDING_RATE',
      market: 'ETHUSDT_UMCBL',
      instrumentType: 'PERPETUAL_FUTURES',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget V2 Mix Market API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v2/mix/market/current-fund-rate?symbol=ETHUSDT_UMCBL&productType=USDT-FUTURES',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: '0.0082',
    unit: '%',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_4'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_funding',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC perpetual funding rate is +0.0125% (elevated leverage premium).',
    category: 'FUNDING_RATE',
    stance: 'CONTRADICTING',
    nature: 'NUMERIC',
    observation: {
      type: 'FUNDING_RATE',
      market: 'BTCUSDT_UMCBL',
      instrumentType: 'PERPETUAL_FUTURES',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Bitget V2 Mix Market API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v2/mix/market/current-fund-rate?symbol=BTCUSDT_UMCBL&productType=USDT-FUTURES',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: '0.0125',
    unit: '%',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_4'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_dom',
    thesisId: 'th_eth_btc_48h',
    claim: 'Estimated BTC market cap dominance expanded to 57.8%, adding +0.4% over 24 hours.',
    category: 'MACRO_METRIC',
    stance: 'CONTRADICTING',
    nature: 'NUMERIC',
    observation: {
      type: 'LAST_PRICE',
      market: 'BTC_DOMINANCE',
      instrumentType: 'SPOT',
      providerSymbol: 'BTC.D',
    },
    provenance: {
      sourceName: 'Dissent Macro Desk Feed',
      sourceType: 'DERIVED_ANALYTICS',
      endpointOrLocator: 'dissent://macro/dominance/btc',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: '57.8',
    unit: '%',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_1'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_ob_depth',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH/USDT spot top-of-book bid/ask depth ratio is 1.18 within 1% depth.',
    category: 'ORDERBOOK_DEPTH',
    stance: 'SUPPORTING',
    nature: 'DERIVED',
    observation: {
      type: 'LAST_PRICE',
      market: 'ETH/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot Orderbook',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/orderbook?symbol=ETHUSDT&type=step0&limit=50',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
    },
    value: '1.18',
    unit: 'ratio',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_2'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_ob_depth',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC/USDT spot top-of-book bid/ask depth ratio is 0.94 within 1% depth.',
    category: 'ORDERBOOK_DEPTH',
    stance: 'CONTRADICTING',
    nature: 'DERIVED',
    observation: {
      type: 'LAST_PRICE',
      market: 'BTC/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot Orderbook',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/orderbook?symbol=BTCUSDT&type=step0&limit=50',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
    },
    value: '0.94',
    unit: 'ratio',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_oi',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH perpetual open interest increased +4.2% over 24h to $840M.',
    category: 'OPEN_INTEREST',
    stance: 'SUPPORTING',
    nature: 'NUMERIC',
    observation: {
      type: 'OPEN_INTEREST',
      market: 'ETHUSDT_UMCBL',
      instrumentType: 'PERPETUAL_FUTURES',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget V2 Mix Market API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v2/mix/market/open-interest?symbol=ETHUSDT_UMCBL&productType=USDT-FUTURES',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: 840000000,
    unit: 'USD',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_4'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_oi',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC perpetual open interest grew +1.1% over 24h to $2.91B.',
    category: 'OPEN_INTEREST',
    stance: 'NEUTRAL',
    nature: 'NUMERIC',
    observation: {
      type: 'OPEN_INTEREST',
      market: 'BTCUSDT_UMCBL',
      instrumentType: 'PERPETUAL_FUTURES',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Bitget V2 Mix Market API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v2/mix/market/open-interest?symbol=BTCUSDT_UMCBL&productType=USDT-FUTURES',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: 2910000000,
    unit: 'USD',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_liq_24h',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH perpetual short liquidations ($18.4M) exceeded longs ($4.2M) over 24h.',
    category: 'LIQUIDATION_FLOW',
    stance: 'SUPPORTING',
    nature: 'NUMERIC',
    observation: {
      type: 'BASE_VOLUME_24H',
      market: 'ETHUSDT_UMCBL',
      instrumentType: 'PERPETUAL_FUTURES',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Bitget Derivatives Liquidation Feed',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v2/mix/market/liquidation',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: 18400000,
    unit: 'USD',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_rsi_4h',
    thesisId: 'th_eth_btc_48h',
    claim: 'ETH 4H Relative Strength Index is 58.4 (constructive neutral momentum).',
    category: 'PRICE_ACTION',
    stance: 'SUPPORTING',
    nature: 'DERIVED',
    observation: {
      type: 'INTERVAL_PRICE_CHANGE',
      market: 'ETH/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'ETHUSDT',
    },
    provenance: {
      sourceName: 'Dissent Technical Engine',
      sourceType: 'DERIVED_ANALYTICS',
      endpointOrLocator: 'dissent://technical/rsi/ETHUSDT/4h',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: '58.4',
    unit: 'index',
    derivedFromEvidenceIds: ['ev_eth_last'],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_rsi_4h',
    thesisId: 'th_eth_btc_48h',
    claim: 'BTC 4H Relative Strength Index is 62.1 (approaching upper consolidation resistance).',
    category: 'PRICE_ACTION',
    stance: 'CONTRADICTING',
    nature: 'DERIVED',
    observation: {
      type: 'INTERVAL_PRICE_CHANGE',
      market: 'BTC/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'BTCUSDT',
    },
    provenance: {
      sourceName: 'Dissent Technical Engine',
      sourceType: 'DERIVED_ANALYTICS',
      endpointOrLocator: 'dissent://technical/rsi/BTCUSDT/4h',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 300,
    },
    value: '62.1',
    unit: 'index',
    derivedFromEvidenceIds: ['ev_btc_last'],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_eth_1h_ret',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget ETH/USDT spot changed +1.45% over the latest 1H candle interval.',
    category: 'PRICE_ACTION',
    stance: 'SUPPORTING',
    nature: 'NUMERIC',
    observation: {
      type: 'INTERVAL_PRICE_CHANGE',
      market: 'ETH/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'ETHUSDT',
      interval: '1H',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot Candles API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/candles?symbol=ETHUSDT&granularity=1h',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
    },
    value: '+1.45',
    unit: '%',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: ['asm_2'],
    verifiable: true,
    schemaVersion: 1,
  },
  {
    id: 'ev_btc_1h_ret',
    thesisId: 'th_eth_btc_48h',
    claim: 'Bitget BTC/USDT spot changed +0.32% over the latest 1H candle interval.',
    category: 'PRICE_ACTION',
    stance: 'NEUTRAL',
    nature: 'NUMERIC',
    observation: {
      type: 'INTERVAL_PRICE_CHANGE',
      market: 'BTC/USDT',
      instrumentType: 'SPOT',
      providerSymbol: 'BTCUSDT',
      interval: '1H',
    },
    provenance: {
      sourceName: 'Bitget V3 Spot Candles API',
      sourceType: 'EXCHANGE_API',
      endpointOrLocator: 'https://api.bitget.com/api/v3/market/candles?symbol=BTCUSDT&granularity=1h',
      observedAt: OBSERVED_AT,
      retrievedAt: NOW,
      freshnessMode: 'AGE_SINCE_OBSERVATION',
      freshnessWindowSeconds: 60,
    },
    value: '+0.32',
    unit: '%',
    derivedFromEvidenceIds: [],
    relatedAssumptionIds: [],
    verifiable: true,
    schemaVersion: 1,
  },
];

export const PROTOTYPE_ADVOCATE_CASE: ArgumentV1 = {
  id: 'arg_adv_eth_btc',
  thesisId: 'th_eth_btc_48h',
  stance: 'ADVOCATE',
  summary:
    'ETH exhibits expanding spot turnover, persistent orderbook buy support, and superior short-horizon relative momentum without excessive derivatives heating.',
  points: [
    {
      id: 'pt_adv_1',
      title: 'Spot Turnover & Orderbook Asymmetry',
      reasoning:
        'Turnover on ETH spot pairs expanded to $1.42B with bids outweighing asks 1.18x within 1% depth, confirming authentic organic spot demand rather than purely speculative leverage.',
      evidenceIds: ['ev_eth_vol_24h', 'ev_eth_ob_depth'],
      targetAssumptionIds: ['asm_2'],
      weight: 'PRIMARY',
    },
    {
      id: 'pt_adv_2',
      title: '1H Spread Outperformance Momentum',
      reasoning:
        'ETH delivered +1.45% in the trailing 1H window against BTC +0.32%, producing a +1.13 percentage point return spread that confirms short-horizon relative leadership.',
      evidenceIds: ['ev_spread_1h', 'ev_eth_1h_ret'],
      targetAssumptionIds: ['asm_2'],
      weight: 'PRIMARY',
    },
    {
      id: 'pt_adv_3',
      title: 'Favorable Derivatives Carry Cost',
      reasoning:
        'ETH perpetual funding (+0.0082%) sits significantly lower than BTC funding (+0.0125%), allowing relative long positions to be held with lower carry degradation.',
      evidenceIds: ['ev_eth_funding', 'ev_btc_funding'],
      targetAssumptionIds: ['asm_4'],
      weight: 'SECONDARY',
    },
    {
      id: 'pt_adv_4',
      title: 'Open Interest Inflow Skew',
      reasoning:
        'ETH contract open interest grew +4.2% in 24 hours, outpacing BTC OI expansion (+1.1%), indicating capital rotation into ETH exposure.',
      evidenceIds: ['ev_eth_oi', 'ev_btc_oi'],
      targetAssumptionIds: ['asm_4'],
      weight: 'SECONDARY',
    },
    {
      id: 'pt_adv_5',
      title: 'Short Liquidation Tailwinds',
      reasoning:
        'A 4.4:1 ratio of short liquidations over longs ($18.4M short vs $4.2M long) clears overhead technical resistance, encouraging momentum buyers.',
      evidenceIds: ['ev_liq_24h'],
      targetAssumptionIds: [],
      weight: 'CONTEXTUAL',
    },
  ],
  risksOrCounterweightsConsidered: [
    'BTC dominance remains structurally elevated at 57.8%.',
    'Broad altcoin breadth beyond ETH remains constrained.',
  ],
  createdAt: NOW,
  schemaVersion: 1,
};

export const PROTOTYPE_DISSENTER_CASE: ArgumentV1 = {
  id: 'arg_diss_eth_btc',
  thesisId: 'th_eth_btc_48h',
  stance: 'DISSENTER',
  summary:
    'Structural BTC dominance at 57.8%, heavier institutional ETF liquidity gravity, and thin altcoin breadth create severe downside resistance against sustainable relative outperformance.',
  points: [
    {
      id: 'pt_diss_1',
      title: 'BTC Dominance & Structural Capital Gravity',
      reasoning:
        'BTC dominance climbed to 57.8% (+0.4% in 24h), indicating that broader institutional capital remains firmly anchored in Bitcoin rather than dispersing into smart-contract platforms.',
      evidenceIds: ['ev_btc_dom', 'ev_btc_last'],
      targetAssumptionIds: ['asm_1'],
      weight: 'PRIMARY',
    },
    {
      id: 'pt_diss_2',
      title: 'Relative Liquidity Concentration Disparity',
      reasoning:
        'BTC 24h spot turnover of $3.89B dwarfs ETH turnover of $1.42B by 2.7x, meaning ETH order depth is significantly more vulnerable to sudden liquidity shocks and margin drains.',
      evidenceIds: ['ev_btc_vol_24h', 'ev_eth_vol_24h'],
      targetAssumptionIds: ['asm_1'],
      weight: 'PRIMARY',
    },
    {
      id: 'pt_diss_3',
      title: 'BTC Overhead Momentum Stall Risk',
      reasoning:
        'BTC 4H RSI has reached 62.1 near range highs, while BTC orderbook shows ask overhang (0.94 bid/ask ratio). A rejection at BTC resistance typically triggers sharper drawdowns in ETH.',
      evidenceIds: ['ev_btc_rsi_4h', 'ev_btc_ob_depth'],
      targetAssumptionIds: ['asm_3'],
      weight: 'SECONDARY',
    },
    {
      id: 'pt_diss_4',
      title: 'Fragility of Altcoin Risk Regime',
      reasoning:
        'The assumption that broad risk appetite is improving is uncorroborated outside of isolated intraday spikes; spot market depth across ETH pairs remains below historical bull regime medians.',
      evidenceIds: ['ev_ratio_last', 'ev_btc_dom'],
      targetAssumptionIds: ['asm_1'],
      weight: 'SECONDARY',
    },
    {
      id: 'pt_diss_5',
      title: 'Historical 48-Hour Mean Reversion Friction',
      reasoning:
        'Short-horizon momentum bursts (+1.13% spread) in ETH/BTC have frequently mean-reverted over 24-48 hours during periods where BTC dominance is in an uptrend.',
      evidenceIds: ['ev_spread_1h'],
      targetAssumptionIds: [],
      weight: 'CONTEXTUAL',
    },
  ],
  risksOrCounterweightsConsidered: [
    'ETH orderbook bids within 1% currently exceed asks by 1.18x.',
    'Perpetual funding rate for ETH remains disciplined and non-frothy.',
  ],
  createdAt: NOW,
  schemaVersion: 1,
};

export const PROTOTYPE_BRIEF: DissentBriefV1 = {
  id: 'brf_eth_btc_48h',
  runId: 'run_inst_0921',
  createdAt: NOW,
  originalThesis:
    'I think ETH will outperform BTC over the next 48 hours because risk appetite is improving and ETH momentum is strengthening.',
  structuredThesis: {
    id: 'th_eth_btc_48h',
    thesisInputId: 'inp_eth_btc_48h',
    originalThesis:
      'I think ETH will outperform BTC over the next 48 hours because risk appetite is improving and ETH momentum is strengthening.',
    market: 'ETH/BTC',
    baseAsset: 'ETH',
    quoteAsset: 'BTC',
    claim: 'ETH will outperform BTC over the next 48 hours',
    direction: 'RELATIVE_LONG',
    timeHorizon: { description: '48 hours', estimatedHours: 48 },
    catalysts: ['improving risk appetite', 'strengthening ETH spot momentum'],
    createdAt: NOW,
    schemaVersion: 1,
  },
  supportingEvidence: PROTOTYPE_EVIDENCE_ITEMS.filter((item) => item.stance === 'SUPPORTING'),
  theDissent: PROTOTYPE_DISSENTER_CASE,
  assumptions: [
    {
      id: 'asm_1',
      thesisId: 'th_eth_btc_48h',
      claim: 'Risk appetite is broadening from BTC into smart contract platforms.',
      type: 'EXPLICIT',
      category: 'MARKET_REGIME',
      status: 'QUESTIONED',
      challenge: 'Capital remains concentrated in BTC ETF vehicles; altcoin breadth remains narrow.',
      invalidationCondition: 'BTC dominance pushes above 58.5% on a daily close.',
      supportingEvidenceIds: ['ev_eth_vol_24h'],
      opposingEvidenceIds: ['ev_btc_dom', 'ev_btc_vol_24h'],
      createdAt: NOW,
      schemaVersion: 1,
    },
    {
      id: 'asm_2',
      thesisId: 'th_eth_btc_48h',
      claim: 'ETH spot turnover and bid absorption reflect authentic institutional accumulation.',
      type: 'EXPLICIT',
      category: 'LIQUIDITY',
      status: 'SUPPORTED',
      challenge: 'Spot volume spikes may represent short-covering rather than long accumulation.',
      invalidationCondition: 'ETH/USDT 24h volume drops below $1.0B while depth collapses.',
      supportingEvidenceIds: ['ev_eth_vol_24h', 'ev_eth_ob_depth', 'ev_spread_1h'],
      opposingEvidenceIds: [],
      createdAt: NOW,
      schemaVersion: 1,
    },
    {
      id: 'asm_3',
      thesisId: 'th_eth_btc_48h',
      claim: 'BTC price will remain rangebound without a violent breakout that drains altcoin liquidity.',
      type: 'INFERRED',
      category: 'CORRELATION',
      status: 'UNTESTED',
      challenge: 'A sudden BTC impulse absorbs all market liquidity, causing ETH/BTC to bleed.',
      invalidationCondition: 'BTC 1H volatility exceeds 3.5% with directional breakout.',
      supportingEvidenceIds: [],
      opposingEvidenceIds: ['ev_btc_rsi_4h'],
      createdAt: NOW,
      schemaVersion: 1,
    },
    {
      id: 'asm_4',
      thesisId: 'th_eth_btc_48h',
      claim: 'Derivatives positioning on ETH is balanced and not overstretched.',
      type: 'INFERRED',
      category: 'POSITIONING',
      status: 'SUPPORTED',
      challenge: 'Rapid perpetual open interest growth could trigger cascading long liquidations.',
      invalidationCondition: 'ETH funding rate spikes above +0.03% per 8 hours.',
      supportingEvidenceIds: ['ev_eth_funding', 'ev_eth_oi'],
      opposingEvidenceIds: [],
      createdAt: NOW,
      schemaVersion: 1,
    },
  ],
  contradictions: [
    {
      id: 'ct_1',
      targetType: 'ASSUMPTION',
      targetId: 'asm_1',
      statement: 'Thesis assumes broadening risk appetite, but BTC Dominance increased +0.4% to 57.8%.',
      contradictingEvidenceId: 'ev_btc_dom',
      explanation:
        'When market risk appetite broadens, capital traditionally rotates down the liquidity curve, reducing BTC dominance. Here, BTC dominance rose, indicating that risk remains defensive.',
      severity: 'SIGNIFICANT',
    },
  ],
  stressScenarios: [
    {
      id: 'sc_1',
      thesisId: 'th_eth_btc_48h',
      name: 'BTC Dominance Expansion Surge',
      description:
        'Institutional spot ETF allocations drive BTC past $65,000, draining altcoin liquidity pools and compressing the ratio.',
      affectedAssumptionIds: ['asm_1', 'asm_3'],
      relevantEvidenceIds: ['ev_btc_dom', 'ev_btc_last', 'ev_ratio_last'],
      transmissionMechanism:
        'Fast institutional inflows into spot BTC ETFs generate cross-pair selling of ETH/BTC by market makers rebalancing delta, causing ratio compression.',
      scenarioType: 'LIQUIDITY_SHOCK',
      plausibility: 'HIGH',
      consequenceForThesis:
        'ETH/BTC breaks below 0.0405 support towards 0.0385, invalidating relative outperformance.',
      uncertainties: ['Net daily ETF inflow magnitude', 'CME futures basis spread reaction'],
      schemaVersion: 1,
    },
    {
      id: 'sc_2',
      thesisId: 'th_eth_btc_48h',
      name: 'Macro Liquidity Shock & Flight to Quality',
      description:
        'Surprise Treasury yield spikes trigger broad market de-risking, hitting high-beta crypto assets first.',
      affectedAssumptionIds: ['asm_1', 'asm_4'],
      relevantEvidenceIds: ['ev_btc_funding', 'ev_eth_vol_24h'],
      transmissionMechanism:
        'Cross-asset margin calls force liquidations of higher-beta tokens, causing ETH to sell off more aggressively than BTC.',
      scenarioType: 'MACRO_REGIME_CHANGE',
      plausibility: 'MEDIUM',
      consequenceForThesis:
        'ETH experiences steeper percentage drawdowns than BTC, driving ETH/BTC to multi-week lows.',
      uncertainties: ['Federal Reserve speaker tone', 'DXY index reaction'],
      schemaVersion: 1,
    },
  ],
  invalidationConditions: [
    {
      id: 'inv_1',
      type: 'QUANTITATIVE',
      thesisId: 'th_eth_btc_48h',
      targetAssumptionIds: ['asm_2'],
      relevantEvidenceIds: ['ev_ratio_last'],
      statement: 'ETH/BTC ratio closes below 0.0405 on 4-hour candle chart.',
      targetMetric: 'ETH/BTC 4H close',
      triggerThreshold: '< 0.0405',
      timeframe: '48 hours',
      observableDataSource: 'Bitget Spot Derived Pair',
      urgency: 'IMMEDIATE_EXIT',
      schemaVersion: 1,
    },
    {
      id: 'inv_2',
      type: 'QUANTITATIVE',
      thesisId: 'th_eth_btc_48h',
      targetAssumptionIds: ['asm_1'],
      relevantEvidenceIds: ['ev_btc_dom'],
      statement: 'BTC Dominance index breaks and holds above 58.5%.',
      targetMetric: 'BTC.D daily close',
      triggerThreshold: '> 58.5%',
      timeframe: '48 hours',
      observableDataSource: 'Macro Desk Index',
      urgency: 'THESIS_REVIEW',
      schemaVersion: 1,
    },
    {
      id: 'inv_3',
      type: 'QUANTITATIVE',
      thesisId: 'th_eth_btc_48h',
      targetAssumptionIds: ['asm_2'],
      relevantEvidenceIds: ['ev_eth_vol_24h', 'ev_btc_vol_24h'],
      statement: 'ETH 24H spot volume drops below $1.0B while BTC volume remains above $3.5B.',
      targetMetric: 'ETH 24H Volume',
      triggerThreshold: '< 1000000000',
      timeframe: '24 hours',
      observableDataSource: 'Bitget Spot Tickers',
      urgency: 'THESIS_REVIEW',
      schemaVersion: 1,
    },
    {
      id: 'inv_4',
      type: 'QUALITATIVE',
      thesisId: 'th_eth_btc_48h',
      targetAssumptionIds: ['asm_4'],
      relevantEvidenceIds: ['ev_eth_funding', 'ev_btc_funding'],
      statement: 'ETH perpetual funding rate surges above BTC funding rate by more than 0.02% per 8h.',
      observableEvent: 'ETH Funding > BTC Funding + 0.02%',
      verificationSource: 'Bitget Mix Funding API',
      expectedWindow: '8 hours',
      urgency: 'WATCHLIST_ONLY',
      schemaVersion: 1,
    },
  ],
  unknowns: [
    'Upcoming US macroeconomic speech tone and its immediate effect on risk asset liquidity.',
    'Off-exchange institutional OTC rebalancing volume between ETH and BTC not visible in orderbook depth.',
    'Potential large ETH staking withdrawal or validator queue changes over the 48-hour window.',
  ],
  evidenceLedger: {
    id: 'led_eth_btc_48h',
    thesisId: 'th_eth_btc_48h',
    items: PROTOTYPE_EVIDENCE_ITEMS,
    summary: {
      totalCount: PROTOTYPE_EVIDENCE_ITEMS.length,
      supportingCount: PROTOTYPE_EVIDENCE_ITEMS.filter((i) => i.stance === 'SUPPORTING').length,
      contradictingCount: PROTOTYPE_EVIDENCE_ITEMS.filter((i) => i.stance === 'CONTRADICTING').length,
      neutralCount: PROTOTYPE_EVIDENCE_ITEMS.filter((i) => i.stance === 'NEUTRAL').length,
      staleCountAtAssembly: 0,
      categoriesPresent: ['PRICE_ACTION', 'ORDERBOOK_DEPTH', 'FUNDING_RATE', 'OPEN_INTEREST', 'LIQUIDATION_FLOW', 'MACRO_METRIC', 'CORRELATION'],
    },
    assembledAt: NOW,
    schemaVersion: 1,
  },
  humanDecision: null,
  disclaimer:
    'Dissent is decision-support research infrastructure, not financial advice, automated trading, or an execution system. All trading decisions are made solely by the human trader.',
  schemaVersion: 1,
};
